# Generated by Django 3.0.3 on 2020-02-19 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kennywoodapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ('starttime',), 'verbose_name': ('itinerary',), 'verbose_name_plural': ('itineraries',)},
        ),
        migrations.AlterField(
            model_name='attraction',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attractions', to='kennywoodapi.ParkArea'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kennywoodapi.Attraction'),
        ),
    ]
